name: Dependabot Auto-merge

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  automerge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Enable automerge for Dependabot PRs
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge --squash --auto "$PR_NUMBER"
